name: Go

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Test
        run: go test -v ./...

      - name: Calc coverage
        run: go test -v -covermode=count -coverprofile=coverage.out
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.8

      - name: Build
        run: go build -v ./...

      - name: Build and push
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: raynkami/uxti.kerb
          tags: latestv5
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
